vanthome/winston-elasticsearch

- bulk_writer.js
The logger threw silently when using the same field with different types
> Log to console on elasticsearch errors

- README.md
- index.js
- test/request_logentry_1.json
- test/test.js
- transformer.js
`winston` allows logging loose metadata that is not just a JSON object. However, due to the constraints of Elasticsearch's `dynamic` field for object datatypes, `winston-elasticsearch` has to enforce (at least for the default Elasticsearch mapping template) that `meta` is an object. Currently it does not. This leads to lost logs if just a single log has a concrete value rather than an object in metadata, because Elasticsearch will error out the bulk request.
This PR just splats into a meta object which gets passed to the transformer.
> splat metadata

- index.js
* improves coverage by removing unused functions and condensing lines
* uses `Object.assign` instead of `...` rest operator to support node6
> Use object assign for node6

- .gitignore
- README.md
- bulk_writer.js
- index.js
- test/request_logentry_1.json
- test/test.js
In a recent project I had the challenge to enable a better logging. Therefore I added two options to winston-elasticsearch:
Option 1: Enable to use a function for option property indexPrefix to use a variable name for the log.
Option 2: Introduced the indexInterfix property to be used in the log transformer to create individual logs for each log entry like prefix-interfix-suffix.
> Added two possibilities to expand the index name

- bulk_writer.js
- index.js
Hey,
```
process.on('uncaughtException', err => {
logger.error('uncaughtException', err, {stack: err.stack});
logger.on('finish', () => process.exit(1));
logger.end();
});
```
In this code in case of uncaught exception we could lose logs, because `winston-elasticsearch` transport calls callback inside `log()` instantly, but it supposed to do it after log delivery (or an error, but it more complex ;) )
> Fire callback to inform winston about log delivery in time

- bulk_writer.js
Issue: flush called twice after each interval instead of once
Reason: Two ticks are getting scheduled
Solution: No need to call tick at the start since this.checkEsConnection()
is already doing that
> Issue: flush called twice after each interval instead of once

- bulk_writer.js
- index.js
de6e51f37a20b683b76f71ae10038a86736e1058 introduced the wrong use of callback in `log(info, callback)` which lead to the following issues:
- the @timestamp is wrong because the transformer is only called every 2 seconds by default (flushInterval for bulk write)
- other transports are stopped for flushInterval because the callback isn't called
For further information about correct use of the callback please read https://github.com/winstonjs/winston/blob/master/lib/winston/logger.js
For tests please clone https://github.com/litti/test-winston-elasticsearch and change the version of winston-elasticsearch in package.json to 0.7.3, 0.7.4 and git+https://github.com/litti/winston-elasticsearch.git. After each change run `node app.js`. Watch the logs in console and the timestamps in your …
> The callback of log(info, callback) was used in a wrong manner

- index.js
We are NOT able to pass the **actual timestamp** into transformer, always the **postponed timestamp** (`new Date().toISOString()`) gets logged. This leads to **wrong/delayed** timestamp log.
```js
log(info, callback) {
const { level, message } = info;
const meta = Object.assign({}, _.omit(info, ['level', 'message']));
setImmediate(() => {
this.emit('logged', level);
});
const logData = {
message,
level,
meta,
};
const entry = this.opts.transformer(logData); // logData never has `timestamp`
....
}
```
```js
const transformer = function transformer(logData) {
const transformed = {};
transformed['@timestamp'] = logData.timestamp ? logData.timestamp : new Date().toISOString();
transformed.message = logData.message;
transformed.severity = logData.level;
transformed.fields = logData.meta; …
```
> Get timestamp from info

- bulk_writer.js
- test/test.js
Each object of buffer is expected to have 3 keys: index, type and doc.
While creating body each object of buffer is broken into 2 object, so while rollback merged these 2 object back into one before adding into buffer.
This pull request also fixes https://github.com/vanthome/winston-elasticsearch/issues/89
> properly updated buffer(bulk array) while rollback.

- index.d.ts
In all three API references ([5.x](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/5.x/api-reference.html#_bulk), [6.x](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/6.x/api-reference.html#_bulk), [7.x](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/api-reference.html#_bulk)) it is said:
So this PR refines the type.
> Refine the type of waitForActiveShards field

- bulk_writer.js
1. Let's look at the following code:
```js
BulkWriter.prototype.write = function write(body) {
const thiz = this;
return this.client.bulk({
// ...
type: this.type,
}).then(...)
```
`this.type === undefined`, cause `this` points to the `write` [function context](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/this#Function_context). So you should be very careful with it.
2. The other thing to keep in mind is that according to [the reference](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/7.x/api-reference.html#_bulk) `type` field can be passed to API. But if you check out the source code of elastic-search js client, [bulk.js#L67](https://github.com/elastic/elasticsearch-js/blob/5263c56fdaff093894760c754d67f02249683c78/api/api/bulk.js#L67), …
> Don't pass redundant "type" field

- README.md
README wasn't updated when `elasticsearch` was deprecated in favor of `@elastic/elasticsearch` and this package moved to it. The old URL linking to docs for clientOpts 404s on the elastic website (https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/configuration.html vs https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/current/client-configuration.html)
> Fix references to elasticsearch package in README

- bulk_writer.js
Now index template always have index pattern as `logs-*`, but there is option to change index prefix, we need to take into account that.
> Index pattern should be based on specified index prefix

- .eslintrc
- bulk_writer.js
ElasticSearch official client now return API response at `body` property among meta-information like `statusCode` or `headers`.
https://www.npmjs.com/package/@elastic/elasticsearch#quick-start
Need to correctly handle that change.
> ES client has new return format

- index.d.ts
Updated part of `index.d.ts` which was causing problems with typescript - `ElasticsearchTransport` not being seen by ts as type of TransportStream
> fix typescript error

- bulk_writer.js
- This could happen when the schema change, adding or removing fields.
- The fix just verifies and prevent the response.body exist before be used.
- No side effects found since this is a tiny fix.
> - When this.client.bulk is called, response.body returns an empty object

- README.md
- index.js
- transformer.js
- update the readme including how to use
- update the transformer so one can inject own traces
- update the constructor with reference to the apm module
- update the log function to use the client or the user's own apm traces
---
I know this was not an open issue though I needed this feature.
APM logs lets you know how long a functions takes, as well as its subsequent calls (e.g. database):
[source](https://www.elastic.co/apm)
With this feature, one can use kibana [logs apm integration](https://www.elastic.co/guide/en/kibana/current/xpack-logs-using.html#logs-integrations) to get more insight from their logs
> Instrument logs with elastic-apm traces

- index.js
This pr fixes #127 
Description from issue:
0.8.6 introduced a breaking change in the way the library is exported, exporting {ElasticSearchTransport} instead of ElasticSearchTransport.
it looks like it was introduced in: https://github.com/vanthome/winston-elasticsearch/pull/126
> breaking change in 0.8.6

- bulk_writer.js
Hi @vanthome!
I'd like to start by saying how much I appreciate that you took the time to write this transport - I've used it often and it's wonderful.
Would you consider removing the console statement as proposed in this PR, or consider a strategy in which it can be switched off?
We have a proxy setup to elasticsearch and when we are configuring it on the fly, it can result in the client console output exploding due to expected failures `ResponseError`. There is a debug statement already that you have that I think works quite well, although for user friendliness I can see why you've opted to output it by default.
What do you think?
> Remove console statement on bulk write error

- bulk_writer.js
- index.js
- package-lock.json
Fixes #139 
Currently the buffer fills up with failed documents. This commit adds a retry counter - after the number of retries has been exceeded then the document is discarded.
> Implemented retries for failed documents

- .eslintrc
- .travis.yml
- bulk_writer.js
- index-template-mapping.json
- index.js
- test/test.js
This (winston) transport is currently holding Timers (i.e. `setTimeout`) in place when `buffering === true` through calls between [`BulkWriter.prototype.tick`](https://github.com/vanthome/winston-elasticsearch/blob/03414b2c1bd62a2294cb7d61e4d4c0347ee3fff6/bulk_writer.js#L58) and [`BulkWriter.prototype.schedule`](https://github.com/vanthome/winston-elasticsearch/blob/03414b2c1bd62a2294cb7d61e4d4c0347ee3fff6/bulk_writer.js#L41) causing the Node.js runtime to stay alive even though there's nothing more to process.
This PR allows the transport schedule to be paused when no more bulk need to be inserted into ES thus allowing the runtime to be properly stopped.
> Allow process termination even if buffering is enabled

- README.md
- bulk_writer.js
- index-template-mapping-es-gte-7.json
- index-template-mapping-es-lte-6.json
- index-template-mapping.json
- index.d.ts
- index.js
- test/test.js
Seems like the mapping part of json file needs to be wrapped into a "type" (which can be any name). This is on elasticsearch 6. I am not sure if older elastic used to accept without it.
e.g.
```
"mapping": {
"asdasd": {
"properties": { .... }
}
}
```
> fix for broken template mapping json

- index.js
When the user sends the custom traces, the transaction trace is used in all traces(trace, transaction, and span). 
Override with the corresponding trace name.
> Fix custom traces precedence

- bulk_writer.js
- index.d.ts
- package-lock.json
- test/test.js
I used winston-elasticseach to send logs on my ELK. I had some problems with auth on ElasticSearch and that made my server run really slowly because winston couldn't send logs....
I made this pull request to fix those 2 problems:
- Handle invalid transport: It will not emit an error event then, you can handle it as you want in your codebase.
- Handle error on failed report: It will emit an error if one of the bulk reach the max attempt. I think there is an other way to handle that but I give you a begin of idea.
> Handle invalid Transport and fix problem on async loop during error

- README.md
- bulk_writer.js
- index.d.ts
- index.js
- test/test.js
In the most minimal sense, the only thing required to make a datastream work is to change `index` to `create` in the bulk action, and then for either `index` to match `logs-*.*` or to match a the user's custom template pattern.
However by explicitly enabling it, we can manage the experience by conforming to the above while still allowing use of `indexPrefix` and `indexInterfix`.  
Here's some of the `README.md` update:
Elasticsearch 7.9 and higher supports [Datstreams](https://www.elastic.co/guide/en/elasticsearch/reference/master/data-streams.html).  
When `dataStream: true` is set, bulk indexing happens with `create` instead of `index`, and also the default naming convention is `logs-*-*`, which will match the built-in [Index template](https://www.elastic.co/guide/en/elasticsearch/refere …
> support Elasticsearch datastreams

- index.d.ts
- package-lock.json
- package.json
elastic-apm-node is not yet compatible with node 15
and produces error when installing
the code actually doesn't use this package except for the types in index.d.ts
so we should be able to remove it safely.
> Optional elastic-apm-node package

- index.d.ts
- index.js
This passes through a retryLimit from the index into the BulkWriter options to allow you to choose how many times to retry (rather than just using 400)
Related to this: https://github.com/vanthome/winston-elasticsearch/issues/165 but it doesn't fix the duplicate retry problem.
> Set retry limit on BulkWriter in config

- .travis.yml
- CHANGELOG.md
- README.md
- bulk_writer.js
- test/test.js
- Fix travis build process (ES JS Client (7.11.2 instead of 11), nodejs 8 deprecated on yargs)
- Fix templateName is undefined or null if options.index is undefined or null
- Correct npm link in README.md (browsenpm.org isn't connected to npm anymore)
> Build process fixed, two minor things fixed

- README.md
- index.js
There is no way to extend the default transformer, This PR allow importing the default transformer and show an example of how to extend it.
> Export the default transformer

- index.d.ts
There is no way to import `ElasticsearchTransformer` with type declaration on typescript, This PR allow import `ElasticsearchTransformer` with type declaration.
Related with: [PR#186](https://github.com/vanthome/winston-elasticsearch/pull/186)
> Add export type declaration for ElasticsearchTransformer

- index.js
Adding this gives the ability to have asynchronous calls in the transformer. Previously if you tried to do this the resulting log would be empty.
> Add ability to make an async log.

- bulk_writer.js
- index.js
According to my issue #211 , I wrote a deadly simple fix to avoid `EMFILE` error.
Instead of read the template file with `fs` module, simple require it as a raw JavaScript object.
Then, inject the template if the given configuration does not contains one.
> chore: fix template mapping import

- bulk_writer.js
The node client for elasticsearch 8 [removed automatically converting options to train_case](https://www.elastic.co/guide/en/elasticsearch/client/javascript-api/8.0/changelog-client.html#_drop_support_for_old_camelcased_keys). This seems to be all that's required for es8 support
> fix: elasticsearch 8 support
